// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn8m6MHU3ZXuf817KtbL8aYtp3w900aWk',
    appId: '1:217679865864:web:7cf99b31fc60e456ddc9bd',
    messagingSenderId: '217679865864',
    projectId: 'trag-efc4c',
    authDomain: 'trag-efc4c.firebaseapp.com',
    storageBucket: 'trag-efc4c.firebasestorage.app',
    measurementId: 'G-J8N79Y9Y57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqENFD_ZZN7FuM4ULxo9l_eEvtD475kLY',
    appId: '1:217679865864:android:6e8ae2e9afb3271dddc9bd',
    messagingSenderId: '217679865864',
    projectId: 'trag-efc4c',
    storageBucket: 'trag-efc4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8AWT4FYhMciKFGaXxQMwrMFXFDuxQnbQ',
    appId: '1:217679865864:ios:dafac4455295cd94ddc9bd',
    messagingSenderId: '217679865864',
    projectId: 'trag-efc4c',
    storageBucket: 'trag-efc4c.firebasestorage.app',
    iosClientId: '217679865864-qga9f1bttdu3269fn7s06pgl1ao4360u.apps.googleusercontent.com',
    iosBundleId: 'com.ecommerce.trag',
  );

}